# ServiceMonitor 用於自動發現 demo-app 的指標
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-metrics
  namespace: monitoring
  labels:
    app: demo-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-app
  namespaceSelector:
    matchNames:
      - demo-app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s

---
# ServiceMonitor 用於 OpenTelemetry Collector
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-otel-collector
  namespace: monitoring
  labels:
    app: demo-app-otel-collector
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: otel-collector
  namespaceSelector:
    matchNames:
      - demo-app
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s