# Fixed values for demo-app
replicaCount: 1

image:
  repository: re4388/demo-app
  pullPolicy: IfNotPresent
  tag: "main-2e4c925"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

# Health checks
healthCheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

# MongoDB configuration - Fixed for official MongoDB image
mongodb:
  enabled: true
  auth:
    enabled: false  # Disable auth for simplicity, can be enabled later
  persistence:
    enabled: true
    size: 8Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  # Use official MongoDB image with correct settings
  image:
    registry: docker.io
    repository: mongo
    tag: "7.0"
  # Correct security context for official MongoDB image
  podSecurityContext:
    enabled: true
    fsGroup: 999  # MongoDB user group
  containerSecurityContext:
    enabled: true
    runAsUser: 999  # MongoDB user ID
    runAsNonRoot: true
    allowPrivilegeEscalation: false

# MinIO configuration
minio:
  enabled: true
  auth:
    rootUser: minioadmin
    rootPassword: "minioadmin123"
  defaultBuckets: "demo-bucket"
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Environment variables for the application
env:
  # MongoDB - No authentication configuration
  SPRING_DATA_MONGODB_HOST: "demo-app-mongodb"
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_DATABASE: "demo"
  # Remove username/password since auth is disabled
  # SPRING_DATA_MONGODB_USERNAME: "demo_user"
  # SPRING_DATA_MONGODB_PASSWORD: "demo_password"

  # MinIO
  MINIO_ENDPOINT: "http://demo-app-minio:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin123"

  # Application
  SPRING_PROFILES_ACTIVE: "kubernetes"

  # Observability
  OTEL_SERVICE_NAME: "demo-app"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=demo-app,service.version=1.0.0"

# ConfigMap for application configuration
configMap:
  enabled: true
  data:
    application.yml: |
      server:
        port: 8080
      spring:
        application:
          name: demo-app
        data:
          mongodb:
            host: ${SPRING_DATA_MONGODB_HOST}
            port: ${SPRING_DATA_MONGODB_PORT}
            database: ${SPRING_DATA_MONGODB_DATABASE}
            # No authentication needed
            # username: ${SPRING_DATA_MONGODB_USERNAME}
            # password: ${SPRING_DATA_MONGODB_PASSWORD}
            # authentication-database: ${SPRING_DATA_MONGODB_DATABASE}
        servlet:
          multipart:
            max-file-size: 100MB
            max-request-size: 100MB
      minio:
        endpoint: ${MINIO_ENDPOINT}
        access-key: ${MINIO_ACCESS_KEY}
        secret-key: ${MINIO_SECRET_KEY}
      management:
        endpoints:
          web:
            exposure:
              include: health,info,metrics,prometheus
        endpoint:
          health:
            show-details: always
            probes:
              enabled: true
        metrics:
          export:
            prometheus:
              enabled: true
      springdoc:
        api-docs:
          path: /v3/api-docs
        swagger-ui:
          path: /swagger-ui.html
          enabled: true
      logging:
        level:
          root: INFO
        pattern:
          console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
