apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: demo-app
data:
  application.yml: |
    server:
      port: 8080
    spring:
      application:
        name: demo-app
      data:
        mongodb:
          host: ${SPRING_DATA_MONGODB_HOST}
          port: ${SPRING_DATA_MONGODB_PORT}
          database: ${SPRING_DATA_MONGODB_DATABASE}
          # No authentication needed since we disabled MongoDB auth
      servlet:
        multipart:
          max-file-size: 100MB
          max-request-size: 100MB
    minio:
      endpoint: ${MINIO_ENDPOINT}
      access-key: ${MINIO_ACCESS_KEY}
      secret-key: ${MINIO_SECRET_KEY}
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
          probes:
            enabled: true
      metrics:
        export:
          prometheus:
            enabled: true
    logging:
      file:
        name: /tmp/application.log  # Use /tmp instead of /app/logs
      level:
        root: INFO