# Docker-specific configuration
server:
  port: 8080

spring:
  application:
    name: demo-app
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:mongodb}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:demo}
      username: ${SPRING_DATA_MONGODB_USERNAME:demo_user}
      password: ${SPRING_DATA_MONGODB_PASSWORD:demo_password}
      authentication-database: ${SPRING_DATA_MONGODB_DATABASE:demo}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

app:
  version: 1.0.0

minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
    tags:
      application: ${spring.application.name}
      environment: ${SPRING_PROFILES_ACTIVE:docker}

logging:
  level:
    com.example.demoapp: INFO
    org.springframework: INFO
    io.opentelemetry: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  file:
    name: /var/log/application.log