# Kubernetes-specific configuration
server:
  port: 8080

spring:
  application:
    name: demo-app
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:demo-app-mongodb}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:demo}
      # No authentication for simplified setup
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

app:
  version: 1.0.0

minio:
  endpoint: ${MINIO_ENDPOINT:http://demo-app-minio:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin123}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
    tags:
      application: ${spring.application.name}
      environment: ${SPRING_PROFILES_ACTIVE:kubernetes}
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  file:
    name: /tmp/application.log
  level:
    com.example.demoapp: INFO
    org.springframework: INFO
    io.opentelemetry: INFO