name: CI/CD 管道

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

# 新增權限設定
permissions:
  contents: write     # 需要寫入權限來推送映像標籤更新
  actions: read
  checks: write
  pull-requests: write

env:
  DOCKER_IMAGE_NAME: re4388/demo-app
  JAVA_VERSION: "17"

jobs:
  # 持續整合 - 執行測試
  ci:
    name: 持續整合
    runs-on: ubuntu-latest

    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v5

      - name: 設定 JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: maven

      - name: 快取 Maven 相依性
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: 執行測試
        working-directory: ./application
        run: mvn clean test

      - name: 上傳測試結果
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            application/target/surefire-reports/
            application/target/site/jacoco/

  # 持續部署 - 建置並推送 Docker 映像檔
  cd:
    name: 持續部署
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v5

      - name: 設定 JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: maven

      - name: 快取 Maven 相依性
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: 建置應用程式
        working-directory: ./application
        run: mvn clean package -DskipTests

      - name: 設定 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登入 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: 提取中繼資料
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: 建置並推送 Docker 映像檔
        uses: docker/build-push-action@v5
        with:
          context: ./application
          file: ./application/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: 更新 Docker Hub 描述
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          repository: ${{ env.DOCKER_IMAGE_NAME }}
          readme-filepath: ./application/README.md

      

      